# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.20.1
minecraft_version_range=[1.20,1.20.2)

# Forge
forge_id=forge
forge_version=47.4.16
forge_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

# Mod
mod_group_id=dev.xcolorful.cgccompat.cgccshader
mod_id=cgccshader
mod_name=CGC Compat: Shader
mod_license=GPL-3.0-only
mod_version=0.0.0
mod_credits=
mod_authors=XiaoColorful
mod_description=Compatibility mod for Custom Gun Continued

mod_issue_url=https://github.com/XColorful/CGC-Compat-Shader/issues
mod_display_url=https://github.com/XColorful/CGC-Compat-Shader/wiki
mod_logo_file=logo.png

pack_description=CGC Compat: Shader resources
pack_format=15

# Mixin
mixin_config_file=cgccshaderclient.mixins.json
mixin_annotation=org.spongepowered:mixin:0.8.5:processor

# Dependencies
customgun_version_range=[0.0.18,)
customgun_local=../libs/customgun-0.0.18-forge-1.20.1.jar

# CompileOnly
